### ISSUE TITLE
token

### ISSUE THREAD

**Issue by Hellohost** [Delavalom/telegram-gpt3#1]
UPSTASH_TOKEN=
what kind of token is needed here?

**Comment by Delavalom** [comment]
When you signin for [Upstash](https://upstash.com/) you can look at the console for the rest token and copied.

Upstash offers serverless caching services with Redis. I came with this solution for now to help persist chat conversation messages, and allow gpt API to have context for each conversation. This service is completely free up to 10,000 requests daily.

![Screen Shot 2023-04-08 at 10 29 58 AM](https://user-images.githubusercontent.com/95777619/230726870-0ab89af0-31a1-432f-8066-8ada5e22e7f6.png)
